version: '3.8'
services:
  authservice:
    build: 
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./authservice/.env
  relservice:
    build: 
      context: ./relservice
      dockerfile: Dockerfile
    env_file:
      - ./relservice/.env
    ports:
      - "8082:8082"
    depends_on:
      - rel_db
  rel_db: 
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: placeholder
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: pirate
      MYSQL_DATABASE: user_relations
    container_name: golang-docker-db-rel
    ports:
      - 33066:3306

