version: '3.8'
services:
  authservice:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./auth-service/.env
  apertium:
    build:
      context: ./apertium
      dockerfile: Dockerfile
    ports:
      - "8081:8081" 
